#!/bin/python3

import requests

d=requests.get("http://temp-mail.org/en/")
content=d.text

string='<input id="mail" onclick="select(this);" data-original-title="Your temporary Email address" class="mail opentip" value="helasameji@shayzam.net" data-placement="bottom" title="" type="text" readonly="">'

firstIndex=str.find('value="')
secondIndex=str.find('" data-placement="bottom" title="" type="text" readonly="">')

print(string.substring(firstIndex, secondIndex))
